default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  encoding: unicode
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  timeout: 5000

development:
  <<: *default
  database: heisigdevelopment

test:
  <<: *default
  database: heisigtest

production:
  <<: *default
  database: heisigproduction
  username: <%= ENV["database_username"] %>
  password: <%= ENV["database_password"] %>