default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  database: heisigdevelopment
  username: postgres
  password: postgres

test:
  <<: *default
  database: heisigtest
  username: postgres
  password: postgres

production:
  <<: *default
  database: heisigproduction
  username: postgres
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
